---
title: "Synthese : espèces animales"
author: "M.Bison"
date: "2026-04-10"
output: pdf_document

knit: (function(input, ...) {
    rmarkdown::render(
      input,
      output_dir = "/Volumes/SHARED/Git_Projects/Regime_alimentaire_chamois/Output"
    )
  })
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load-data, echo=FALSE}
library(ggplot2)

load("../Output/Rdata/species_an_occ1.Rdata")
```

## Etat des lieux des espèces animales échantillonnées

Sur 180 fecès échantillonnées, 115 sont du chamois, 11 du cerf, 4 du chevreuil et 50 n'ont été attribuées à aucune espèce.

```{r plot1, echo=FALSE}
ggplot(species_an_occ1) +
  geom_bar(aes(x=Taxon1)) +
  ylab("Nombre de fecès") +
  xlab("Espèces identifées")
```


```{r plot2, echo=FALSE}
ggplot(species_an_occ1[is.element(species_an_occ1$Taxon1, "Rupicapra rupicapra"),]) +
  geom_bar(aes(x=Date)) +
  ylab("Nombre de fecès")
```


```{r plot3, echo=FALSE}
ggplot(species_an_occ1[is.element(species_an_occ1$Taxon1, "Rupicapra rupicapra"),]) +
  geom_bar(aes(x=as.factor(as.character(Departement)))) +
  ylab("Nombre de fecès") +
  xlab("Département")
```